version: '3.7'

services:

  nginx:
    build:
      context: ./Docker/nginx
    ports:
      - "80:8083"
      - "443:8443"
    volumes:
      - ./Docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf.template
      - ./Docker/nginx/ssl:/etc/nginx/ssl
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/proxy_params:/etc/nginx/proxy_params
      - ./Backend:/var/www/html
      - ./FrontEnd:/var/app/
      - ./Baza:/var/baza/
      - ./Friendly:/var/friendly
      - ./List:/var/list
    user: user
    environment:
      - ENV_ORG_BACKEND_HOST=php
      - ENV_VHOD_BACKEND_HOST=php.vhod
      - ENV_DRUG_BACKEND_HOST=php.drug
      - ENV_SPISOK_BACKEND_HOST=php.spisok
    networks:
      - backend
    links:
      - mysql
      - node
      - phpBaza
      - phpFriendly
      - phpList
      - php

  php:
    hostname: php.org
    image: php:systo
    env_file:
      - ./Backend/.env
    container_name: php-solarSysto
    volumes:
      - ./Backend:/var/www/html
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /var/www/html
    user: user
    environment:
      - WITH_XDEBUG=true
      - WORKING_DIR=/var/www/html
    networks:
      - backend

  phpBaza:
    hostname: php.vhod
    image: php:systo
    container_name: php-baza
    volumes:
      - ./Baza:/var/baza
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /var/baza
    user: user
    environment:
      - WITH_XDEBUG=true
      - WORKING_DIR=/var/baza
    networks:
      - backend

  phpFriendly:
    hostname: php.drug
    image: php:systo
    container_name: php-friendly
    volumes:
      - ./Friendly:/var/friendly
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /var/friendly/html
    environment:
      - WITH_XDEBUG=true
      - WORKING_DIR=/var/friendly
    user: user
    networks:
      - backend

  phpList:
    hostname: php.spisok
    image: php:systo
    container_name: php-list
    volumes:
      - ./List:/var/list
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /var/list
    environment:
      - WITH_XDEBUG=true
      - WORKING_DIR=/var/list
    user: user
    networks:
      - backend

  redis:
    build: ./Docker/redis
    container_name: redis-solarSysto
    command: redis-server --appendonly yes
    ports:
      - "8002:6379"
    networks:
      - backend

  node:
    build:
      context: ./Docker/node
    working_dir: /var/app
    ports:
      - "8081:8080"
    container_name: node-solarSysto
    volumes:
      - ./FrontEnd:/var/app
    command: tail -f /dev/null
    user: node
    networks:
      - backend

  worker:
    build:
      context: ./Docker/worker
    image: 'laravelworker'
    volumes:
      - ./Backend:/var/www/html
      - ./Friendly:/var/friendly
      - ./List:/var/list
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./Docker/worker/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    user: user
    command: [ "supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    networks:
      - backend

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'systo'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'default'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./Docker/mysql/db:/var/lib/mysql
    networks:
      - backend

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=common404"
      - "MYSQL_DATABASE=friendly"
    volumes:
      - ./Docker/mysqlFriendly/db:/var/lib/mysql
      - ./Docker/mysqlFriendly/log/mysql.log:/var/log/mysql/mysql.log
      - ./Docker/mysqlFriendly/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33065:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
