version: '3.7'

services:

  nginx:
    build:
      context: ./Docker/nginx
    ports:
      - "80:8083"
      - "443:8443"
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/nginx/ssl:/etc/nginx/ssl
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/proxy_params:/etc/nginx/proxy_params
      - ./Backend:/var/www/html
      - ./FrontEnd:/var/app/
      - ./Baza:/var/baza/
    user: user
    networks:
      - backend
    links:
      - mysql
      - node
      - phpBaza
      - php

  php:
    build:
      context: ./Docker/php
    image: 'laravelapp'
    container_name: php-solarSysto
    volumes:
      - ./Backend:/var/www/html
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ~/.ssh/id_rsa.pub:/home/user/.ssh/id_rsa.pub
    user: user
    networks:
      - backend

  phpBaza:
    build:
      context: ./Docker/phpBaza
    image: 'laravelbaza'
    container_name: php-baza
    volumes:
      - ./Baza:/var/baza
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    user: user
    networks:
      - backend

  redis:
    build: ./Docker/redis
    container_name: redis-solarSysto
    command: redis-server --appendonly yes
    ports:
      - "8002:6379"
    networks:
      - backend

  node:
    build:
      context: ./Docker/node
    working_dir: /var/app
    ports:
        - "8081:8080"
    container_name: node-solarSysto
    volumes:
      - ./FrontEnd:/var/app
    command: tail -f /dev/null
    user: node
    networks:
      - backend

  worker:
    build:
      context: ./Docker/worker
    image: 'laravelworker'
    volumes:
      - ./Backend:/var/www/html
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./Docker/worker/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    user: user
    command: [ "supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    networks:
      - backend

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'systo'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'default'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./Docker/mysql/db:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
