version: '3.7'

services:

  nginx:
    build:
      context: ./Docker/nginx
    ports:
      - "80:8083"
      - "443:8443"
    volumes:
      - ./Docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf.template
      - ./Docker/nginx/ssl:/etc/nginx/ssl
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/proxy_params:/etc/nginx/proxy_params
      - ./Shared:${ENV_SHARED_PATCH}
      - ./Friendly:${ENV_DRUG_PATCH}
      - ./Docker/nginx/auth.basic:/etc/nginx/auth.basic
    user: user
    environment:
      - ENV_ORG_BACKEND_HOST=${ENV_ORG_BACKEND_HOST}
      - ENV_ORG_FRONTEND_HOST=${ENV_ORG_FRONTEND_HOST}
      - ENV_VHOD_BACKEND_HOST=${ENV_VHOD_BACKEND_HOST}
      - ENV_DRUG_BACKEND_HOST=${ENV_DRUG_BACKEND_HOST}
      - ENV_SPISOK_BACKEND_HOST=${ENV_SPISOK_BACKEND_HOST}

      - ENV_ORG_BACKEND_PATCH=${ENV_ORG_BACKEND_PATCH}
      - ENV_ORG_FRONT_PATCH=${ENV_ORG_FRONT_PATCH}
      - ENV_SHARED_PATCH=${ENV_SHARED_PATCH}
      - ENV_VHOD_PATCH=${ENV_VHOD_PATCH}
      - ENV_DRUG_PATCH=${ENV_DRUG_PATCH}
      - ENV_SPISOK_PATCH=${ENV_SPISOK_PATCH}

    networks:
      - backend
    links:
      - database
      - phpFriendly

  phpFriendly:
    hostname: ${ENV_DRUG_BACKEND_HOST}
    build:
      context: ./Docker/php
      args:
        - WITH_XDEBUG=true
    container_name: php-friendly
    image: 'friendly_laravel'
    env_file:
      - ./Friendly/.env
    volumes:
      - ./Friendly:${ENV_DRUG_PATCH}
      - ./Shared:${ENV_SHARED_PATCH}
    working_dir: ${ENV_DRUG_PATCH}
    environment:
      - WITH_XDEBUG=true
      - WORKING_DIR=${ENV_DRUG_PATCH}
    user: user
    networks:
      - backend

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=common404"
      - "MYSQL_DATABASE=friendly"
    volumes:
      - ./Docker/mysqlFriendly/db:/var/lib/mysql
      - ./Docker/mysqlFriendly/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33065:3306"
    networks:
      - backend

  worker:
    build:
      context: ./Docker/worker
    image: 'laravelworker'
    volumes:
      - ./Friendly:${ENV_DRUG_PATCH}
      - ./Shared:${ENV_SHARED_PATCH}
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./Docker/worker/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    user: user
    command: [ "supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    networks:
      - backend

networks:
  backend:
    driver: bridge
